# Generated by Django 3.1.3 on 2020-11-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formularz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document1', models.FileField(upload_to='')),
                ('document2', models.FileField(upload_to='')),
                ('document3', models.FileField(upload_to='')),
                ('link1', models.CharField(max_length=9999)),
                ('link2', models.CharField(max_length=9999)),
                ('link3', models.CharField(max_length=9999)),
            ],
        ),
    ]
